<?php
//$Id$

// kpr($form);
drupal_add_js(drupal_get_path('module', 'refstats') .'/js/jquery.cookie.js');
drupal_add_js(drupal_get_path('module', 'refstats') .'/js/jquery.popupwindow.js');
drupal_add_js(drupal_get_path('module', 'refstats') .'/js/refstats.js');

function refstats_form_alter(&$form, &$form_state, $form_id) {
//  kpr($form);
  if($form_id == 'ref_txn_node_form') {
//    kpr($form_state);
//    dpm($form_id);
    //kpr($form_state);
    // see http://drupal.org/node/1074616#comment-4218548 for source
    $form['actions']['submit']['#submit'][] = 'refstats_custom_ref_txn_submit';
//    kpr($form);
  }
  if($form_id == 'ref_txn_month_node_form') {
    // see http://drupal.org/node/1074616#comment-4218548 for source
    $form['actions']['submit']['#submit'][] = 'refstats_custom_ref_txn_month_submit';
  }
  if($form_id == 'tour_node_form') {
    // see http://drupal.org/node/1074616#comment-4218548 for source
    $form['actions']['submit']['#submit'][] = 'refstats_custom_tour_submit';
  }
}

/*
 * Implementation of hook_form_FORM_ID_alter().
 *
 * Real-time statistics input form.
 */
function refstats_form_ref_txn_node_form_alter(&$form, &$form_state, $form_id) {
  // add the click-to-increment functionality
//  $form_state['redirect'] = url('node/add/ref-txn');
//  kpr($form_state);
  //tweak input field widths
  $form['field_ref_txn_dir_person']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_person']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_dir_phone']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_phone']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_dir_email']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_email']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_dir_chat']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_chat']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_dir_mail']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_mail']['und'][0]['value']['#maxlength'] = 2;

  $form['field_ref_txn_ref_person']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_person']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_ref_phone']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_phone']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_ref_email']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_email']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_ref_chat']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_chat']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_ref_mail']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_mail']['und'][0]['value']['#maxlength'] = 2;

  $form['field_ref_txn_tech_person']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_person']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_tech_phone']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_phone']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_tech_email']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_email']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_tech_chat']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_chat']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_tech_mail']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_mail']['und'][0]['value']['#maxlength'] = 2;

  $form['field_ref_txn_docs_person']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_person']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_docs_phone']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_phone']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_docs_email']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_email']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_docs_chat']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_chat']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_docs_mail']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_mail']['und'][0]['value']['#maxlength'] = 2;

  // Tooltips on hover
  $form['field_ref_txn_dir_person']['und']['#prefix'] = '<div id="field-ref-txn-dir-person-add-more-wrapper" title="Directional/In-Person">';
  $form['field_ref_txn_dir_phone']['und']['#prefix'] = '<div id="field-ref-txn-dir-phone-add-more-wrapper" title="Directional/Telephone">';
  $form['field_ref_txn_dir_email']['und']['#prefix'] = '<div id="field-ref-txn-dir-email-add-more-wrapper" title="Directional/E-mail">';
  $form['field_ref_txn_dir_chat']['und']['#prefix'] = '<div id="field-ref-txn-dir-chat-add-more-wrapper" title="Directional/IM or Chat">';
  $form['field_ref_txn_dir_mail']['und']['#prefix'] = '<div id="field-ref-txn-dir-mail-add-more-wrapper" title="Directional/Mail">';

  $form['field_ref_txn_ref_person']['und']['#prefix'] = '<div id="field-ref-txn-ref-person-add-more-wrapper" title="Reference/In-Person">';
  $form['field_ref_txn_ref_phone']['und']['#prefix'] = '<div id="field-ref-txn-ref-phone-add-more-wrapper" title="Reference/Telephone">';
  $form['field_ref_txn_ref_email']['und']['#prefix'] = '<div id="field-ref-txn-ref-email-add-more-wrapper" title="Reference/E-mail">';
  $form['field_ref_txn_ref_chat']['und']['#prefix'] = '<div id="field-ref-txn-ref-chat-add-more-wrapper" title="Reference/IM or Chat">';
  $form['field_ref_txn_ref_mail']['und']['#prefix'] = '<div id="field-ref-txn-ref-mail-add-more-wrapper" title="Reference/Mail">';

  $form['field_ref_txn_tech_person']['und']['#prefix'] = '<div id="field-ref-txn-tech-person-add-more-wrapper" title="Technical Assistance/In-Person">';
  $form['field_ref_txn_tech_phone']['und']['#prefix'] = '<div id="field-ref-txn-tech-phone-add-more-wrapper" title="Technical Assistance/Telephone">';
  $form['field_ref_txn_tech_email']['und']['#prefix'] = '<div id="field-ref-txn-tech-email-add-more-wrapper" title="Technical Assistance/E-mail">';
  $form['field_ref_txn_tech_chat']['und']['#prefix'] = '<div id="field-ref-txn-tech-chat-add-more-wrapper" title="Technical Assistance/IM or Chat">';
  $form['field_ref_txn_tech_mail']['und']['#prefix'] = '<div id="field-ref-txn-tech-mail-add-more-wrapper" title="Technical Assistance/Mail">';

  $form['field_ref_txn_docs_person']['und']['#prefix'] = '<div id="field-ref-txn-docs-person-add-more-wrapper" title="Documents/In-Person">';
  $form['field_ref_txn_docs_phone']['und']['#prefix'] = '<div id="field-ref-txn-docs-phone-add-more-wrapper" title="Documents/Telephone">';
  $form['field_ref_txn_docs_email']['und']['#prefix'] = '<div id="field-ref-txn-docs-email-add-more-wrapper" title="Documents/E-mail">';
  $form['field_ref_txn_docs_chat']['und']['#prefix'] = '<div id="field-ref-txn-docs-chat-add-more-wrapper" title="Documents/IM or Chat">';
  $form['field_ref_txn_docs_mail']['und']['#prefix'] = '<div id="field-ref-txn-docs-mail-add-more-wrapper" title="Documents/Mail">';

  // Change text of "select a value"
  $form['field_ref_txn_tax_branch']['und']['#options']['_none'] = 'Select a branch or unit';
  $form['field_ref_txn_tax_sp']['und']['#options']['_none'] = 'Select a service point';
  $form['field_ref_txn_tax_patron']['und']['#options']['_none'] = 'Select patron status';

  $form['actions']['reset'] = array(
    '#type' => 'button',
    '#value' => t('Reset'),
    '#weight' => 10,
    '#prefix' => '<span class="element-hidden" id="reset-button-wrapper">',
    '#suffix' => '</span>',
    '#attributes' => array('onclick' => 'this.form.reset(); return false;'),
  );
//  kpr($form);
}

/*
 * Implementation of hook_form_FORM_ID_alter().
 *
 * Monthly statistics input form
 */
function refstats_form_ref_txn_month_node_form_alter(&$form, &$form_state, $form_id) {
  // add the click-to-increment functionality
//  $form_state['redirect'] = url('node/add/ref-txn');
  kpr($form);
  //tweak input field widths
  $form['field_ref_txn_dir_person']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_person']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_dir_phone']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_phone']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_dir_email']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_email']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_dir_chat']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_chat']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_dir_mail']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_dir_mail']['und'][0]['value']['#maxlength'] = 2;

  $form['field_ref_txn_ref_person']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_person']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_ref_phone']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_phone']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_ref_email']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_email']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_ref_chat']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_chat']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_ref_mail']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_ref_mail']['und'][0]['value']['#maxlength'] = 2;

  $form['field_ref_txn_tech_person']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_person']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_tech_phone']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_phone']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_tech_email']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_email']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_tech_chat']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_chat']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_tech_mail']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_tech_mail']['und'][0]['value']['#maxlength'] = 2;

  $form['field_ref_txn_docs_person']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_person']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_docs_phone']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_phone']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_docs_email']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_email']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_docs_chat']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_chat']['und'][0]['value']['#maxlength'] = 2;
  $form['field_ref_txn_docs_mail']['und'][0]['value']['#size'] = 2;
  $form['field_ref_txn_docs_mail']['und'][0]['value']['#maxlength'] = 2;

  // Tooltips on hover
  $form['field_ref_txn_dir_person']['und']['#prefix'] = '<div id="field-ref-txn-dir-person-add-more-wrapper" title="Directional/In-Person">';
  $form['field_ref_txn_dir_phone']['und']['#prefix'] = '<div id="field-ref-txn-dir-phone-add-more-wrapper" title="Directional/Telephone">';
  $form['field_ref_txn_dir_email']['und']['#prefix'] = '<div id="field-ref-txn-dir-email-add-more-wrapper" title="Directional/E-mail">';
  $form['field_ref_txn_dir_chat']['und']['#prefix'] = '<div id="field-ref-txn-dir-chat-add-more-wrapper" title="Directional/IM or Chat">';
  $form['field_ref_txn_dir_mail']['und']['#prefix'] = '<div id="field-ref-txn-dir-mail-add-more-wrapper" title="Directional/Mail">';

  $form['field_ref_txn_ref_person']['und']['#prefix'] = '<div id="field-ref-txn-ref-person-add-more-wrapper" title="Reference/In-Person">';
  $form['field_ref_txn_ref_phone']['und']['#prefix'] = '<div id="field-ref-txn-ref-phone-add-more-wrapper" title="Reference/Telephone">';
  $form['field_ref_txn_ref_email']['und']['#prefix'] = '<div id="field-ref-txn-ref-email-add-more-wrapper" title="Reference/E-mail">';
  $form['field_ref_txn_ref_chat']['und']['#prefix'] = '<div id="field-ref-txn-ref-chat-add-more-wrapper" title="Reference/IM or Chat">';
  $form['field_ref_txn_ref_mail']['und']['#prefix'] = '<div id="field-ref-txn-ref-mail-add-more-wrapper" title="Reference/Mail">';

  $form['field_ref_txn_tech_person']['und']['#prefix'] = '<div id="field-ref-txn-tech-person-add-more-wrapper" title="Technical Assistance/In-Person">';
  $form['field_ref_txn_tech_phone']['und']['#prefix'] = '<div id="field-ref-txn-tech-phone-add-more-wrapper" title="Technical Assistance/Telephone">';
  $form['field_ref_txn_tech_email']['und']['#prefix'] = '<div id="field-ref-txn-tech-email-add-more-wrapper" title="Technical Assistance/E-mail">';
  $form['field_ref_txn_tech_chat']['und']['#prefix'] = '<div id="field-ref-txn-tech-chat-add-more-wrapper" title="Technical Assistance/IM or Chat">';
  $form['field_ref_txn_tech_mail']['und']['#prefix'] = '<div id="field-ref-txn-tech-mail-add-more-wrapper" title="Technical Assistance/Mail">';

  $form['field_ref_txn_docs_person']['und']['#prefix'] = '<div id="field-ref-txn-docs-person-add-more-wrapper" title="Documents/In-Person">';
  $form['field_ref_txn_docs_phone']['und']['#prefix'] = '<div id="field-ref-txn-docs-phone-add-more-wrapper" title="Documents/Telephone">';
  $form['field_ref_txn_docs_email']['und']['#prefix'] = '<div id="field-ref-txn-docs-email-add-more-wrapper" title="Documents/E-mail">';
  $form['field_ref_txn_docs_chat']['und']['#prefix'] = '<div id="field-ref-txn-docs-chat-add-more-wrapper" title="Documents/IM or Chat">';
  $form['field_ref_txn_docs_mail']['und']['#prefix'] = '<div id="field-ref-txn-docs-mail-add-more-wrapper" title="Documents/Mail">';

  // Change text of "select a value"
  $form['field_ref_txn_tax_branch']['und']['#options']['_none'] = 'Select a branch or unit';
  $form['field_ref_txn_tax_sp']['und']['#options']['_none'] = 'Select a service point';
  $form['field_ref_txn_tax_patron']['und']['#options']['_none'] = 'Select patron status';

  $form['actions']['reset'] = array(
    '#type' => 'button',
    '#value' => t('Reset'),
    '#weight' => 10,
    '#prefix' => '<span class="element-hidden" id="reset-button-wrapper">',
    '#suffix' => '</span>',
    '#attributes' => array('onclick' => 'this.form.reset(); return false;'),
  );
//  kpr($form);
}

/*
 * Implementation of hook_form_FORM_ID_alter().
 */
function refstats_form_tour_node_form_alter(&$form, &$form_state, $form_id) {
  // add the click-to-increment functionality

  $form['actions']['reset'] = array(
    '#type' => 'button',
    '#value' => t('Reset'),
    '#weight' => 10,
    '#prefix' => '<span class="element-hidden" id="reset-button-wrapper">',
    '#suffix' => '</span>',
    '#attributes' => array('onclick' => 'this.form.reset(); return false;'),
  );

  // Change text of "select a value"
  $form['field_ref_txn_tax_branch']['und']['#options']['_none'] = 'Select a branch or unit';
}

/*
 * Custom submit handlers (redirects)
 */

function refstats_custom_ref_txn_submit(&$form, &$form_state) {
// the reason this wasn't working is that I failed to pass $form_state by reference
//  kpr($form_state);
  $form_state['redirect'] = 'add/reference-statistics';
}

function refstats_custom_ref_txn_month_submit(&$form, &$form_state) {
  $form_state['redirect'] = 'add/monthly-reference-statistics';
}

function refstats_custom_tour_submit(&$form, &$form_state) {
  $form_state['redirect'] = 'add/tour';
}

